### ISSUE TITLE
Organize `rosi_py/` subdirectory.

### ISSUE THREAD

**Issue by mkcor** [bayesways/case_studies_Py#5]
Make sure we are tracking what we want to be tracking (see comment at https://github.com/bayesways/case_studies_Py/pull/3).

Possibly organize https://github.com/bayesways/case_studies_Py/tree/master/rosi_py into a project structure.

**Comment by bayesways** [comment]
Added a rosi_py_files folder. Is that what you mean?

**Comment by mkcor** [comment]
Not only.  Please reopen: I want precisely to have a conversation about the project structure.
